export const fruits = [
    "apple",
    "banana",
    "orange",
    "grape",
    "strawberry",
    "blueberry",
    "pineapple",
    "mango",
    "watermelon",
    "kiwi",
    "pear",
    "peach",
    "plum",
    "cherry",
    "raspberry",
    "blackberry",
    "lemon",
    "lime",
    "avocado",
    "pomegranate",
    "fig",
    "passion fruit",
    "guava",
    "coconut",
    "papaya",
    "dragon fruit",
    "lychee",
    "persimmon",
    "nectarine",
    "apricot",
    "cantaloupe",
    "honeydew melon",
    "cranberry",
    "elderberry",
    "grapefruit",
    "tangerine",
    "date",
    "kiwifruit",
    "mulberry",
    "star fruit",
    "quince",
    "boysenberry",
    "mulberry",
    "jackfruit",
    "rhubarb",
    "gooseberry",
    "clementine",
    "kumquat",
    "plantain",
    "soursop",
    "soursop",
    "tamarind",
    "ugli fruit",
    "ackee",
    "cherimoya",
    "longan",
    "durian",
    "rambutan",
    "breadfruit",
    "salak",
    "lychee",
    "mangosteen",
    "horned melon",
    "feijoa",
    "physalis",
    "pawpaw",
    "jabuticaba",
    "kiwano",
    "pulasan",
    "langsat",
    "cupuaçu",
    "sugar apple",
    "sapodilla",
    "acai berry",
    "barbados cherry",
    "bignay",
    "bunchosia",
    "burahem",
    "cai apple",
    "caimito",
    "calabash",
    "cashew apple",
    "chayote",
    "cherimoya",
    "cloudberry",
    "coco de mer",
    "custard apple",
    "doum palm",
    "durian",
    "feijoa",
    "gandaria",
    "goumi",
    "guanabana",
    "hala fruit",
    "honeyberry",
    "huito",
    "ilama",
    "ice cream bean",
    "jujube",
    "katemfe",
    "kiwano",
    "kumquat",
    "lakoocha",
    "lulo",
    "mabolo",
    "marang",
    "medlar",
    "melon pear",
    "monstera deliciosa",
    "noni",
    "palmyra palm fruit",
    "panama berry",
    "papayuelo",
    "passion fruit",
    "pequi",
    "pindaíba",
    "pitaya",
    "pitanga",
    "rhubarb",
    "safou",
    "santol",
    "sapote",
    "soursop",
    "stinking toe",
    "strawberry guava",
    "strawberry pear",
    "surinam cherry",
    "sweet granadilla",
    "tamarillo",
    "thimbleberry",
    "ugli fruit",
    "white sapote",
    "yantok",
    "yumberry",
    "aronia",
    "bamboo shoot",
    "bilberry",
    "blackcurrant",
    "blood orange",
    "boysenberry",
    "breadfruit",
    "cactus pear",
    "cape gooseberry",
    "carissa",
    "chokeberry",
    "cloudberry",
    "cucumber",
    "currant",
    "damson",
    "elderberry",
    "finger lime",
    "goumi",
    "grapefruit",
    "groundcherry",
    "honeyberry",
    "huckleberry",
    "indian prune",
    "jabuticaba",
    "jujube",
    "kiwifruit",
    "loganberry",
    "loquat",
    "mandarin orange",
    "maypop",
    "melon",
    "nance",
    "olallieberry",
    "pepino",
    "pineberry",
    "plantain",
    "pluot",
    "quandong",
    "quince",
    "rowan",
    "salmonberry",
    "saskatoon berry",
    "sea grape",
    "serviceberry",
    "sloe",
    "strawberry tree",
    "tamarillo",
    "tayberry",
    "ugli fruit",
    "white currant",
    "yuzu"
  ];
  